### ISSUE TITLE
Fails to compile on windows 64 bit

### ISSUE THREAD

**Issue by dimon777** [groupon/sparklint#46]
$ sbt compile
```
starting SBT
[info] Loading global plugins from C:\Users\db\.sbt\0.13\plugins
[info] Loading project definition from C:\Users\db\src\sparklint\project
[info] Set current project to sparklint-spark161 (in build file:/C:/Users/db/src/sparklint/)
java.lang.NoSuchMethodError: scalaz.Scalaz$.ToEitherOps(Ljava/lang/Object;)Lscalaz/syntax/EitherOps;
        at coursier.ivy.PropertiesPattern$.parse(Pattern.scala:150)
        at coursier.ivy.IvyRepository$.parse(IvyRepository.scala:271)
        at coursier.ivy.IvyRepository$.apply(IvyRepository.scala:327)
        at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:403)
        at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:263)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:coursierResolution) java.lang.NoSuchMethodError: scalaz.Scalaz$.ToEitherOps(Ljava/lang/Object;)Lscalaz/syntax/EitherOps;
[error] Total time: 1 s, completed Dec 22, 2016 10:45:44 AM
```

$ echo $JAVA_HOME
/c/app/jdk/7u80-win-x64

$ scala -version
Scala code runner version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL

sbt - 0.13

**Comment by roboxue** [comment]
I can only guess the problem from the log but can't help test it. 

1. The exception is thrown before sbt attempts to compile build.sbt, so it is having problem loading the plugin. 
2. It is sbt-coursier plugin that is having problem loading
3. Given the stack trace, it is the sbt-coursier plugin that has issue finding scalaz dependency

It's kind of out of my control since I have no experience with sbt on windows. I can only give some tips
1. Try java8?
2. Check if scalaz is in your ivy cache or not. If the jar is missing, that means it fails to download the dependency jar, clear your ivy cache and try compile again
3. If all you need is to test the server, you can use prebuilt docker image for sparklint server. I have it at https://hub.docker.com/r/roboxue/sparklint/ right now. The final docker hub registry name will change after #44 shipped. example command looks like `docker run -d -p 23763:23763 -v /Users/rxue/Documents/logs/sample_logs:/sparklint_logs groupon/sparklint -d /sparklint_logs -r`
