### ISSUE TITLE
NumberFormatException when using --historyServer

### ISSUE THREAD

**Issue by neggert** [groupon/sparklint#57]
History server is running Spark 2.1.0. Presumably it needs to be parsing the number as a Long rather than an Int.

```
> sbt "run --historyServer https://sparkhistory.bigred.target.com -r"
[info] Loading global plugins from /Users/z001qdp/.sbt/0.13/plugins
[info] Loading project definition from /Users/z001qdp/projects/sparklint/project
[info] Set current project to sparklint-spark201 (in build file:/Users/z001qdp/projects/sparklint/)
[info] Running com.groupon.sparklint.SparklintServer --historyServer https://sparkhistory.bigred.target.com -r
{"level": "INFO ", "timestamp": "2017-05-23 09:25:59,932", "classname": "com.groupon.sparklint.common.CliSparklintConfig", "body": Parsing args: --historyServer https://sparkhistory.bigred.target.com -r}
{"level": "INFO ", "timestamp": "2017-05-23 09:25:59,955", "classname": "com.groupon.sparklint.common.CliSparklintConfig", "body": Parsed into: historyServer, runImmediately}
[error] (run-main-0) java.lang.NumberFormatException: For input string: "1495547575289"
java.lang.NumberFormatException: For input string: "1495547575289"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at jawn.support.json4s.Parser$$anon$1.jint(Parser.scala:15)
	at jawn.support.json4s.Parser$$anon$1.jint(Parser.scala:10)
	at jawn.Parser.parseNum(Parser.scala:188)
	at jawn.Parser.rparse(Parser.scala:392)
	at jawn.AsyncParser.churn(AsyncParser.scala:213)
	at jawn.AsyncParser.finish(AsyncParser.scala:98)
	at jawnstreamz.package$$anonfun$parseJson$1$$anonfun$apply$2.apply(package.scala:31)
	at jawnstreamz.package$$anonfun$parseJson$1$$anonfun$apply$2.apply(package.scala:31)
	at scalaz.stream.Process$$anonfun$onComplete$1.apply(Process.scala:338)
	at scalaz.stream.Process$$anonfun$onComplete$1.apply(Process.scala:338)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115)
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:262)
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:262)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187)
	at scalaz.Free.go2$1(Free.scala:134)
	at scalaz.Free.go(Free.scala:137)
	at scalaz.Free.run(Free.scala:187)
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84)
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$class.go$1(Process.scala:84)
	at scalaz.stream.Process$class.step(Process.scala:97)
	at scalaz.stream.Process$Append.step(Process.scala:641)
	at scalaz.stream.Process$$anonfun$suspendStep$1.apply(Process.scala:106)
	at scalaz.stream.Process$$anonfun$suspendStep$1.apply(Process.scala:105)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115)
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:262)
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:262)
	at scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187)
	at scalaz.Free.go2$1(Free.scala:134)
	at scalaz.Free.go(Free.scala:137)
	at scalaz.Free.run(Free.scala:187)
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84)
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$class.go$1(Process.scala:84)
	at scalaz.stream.Process$class.step(Process.scala:97)
	at scalaz.stream.Process$Append.step(Process.scala:641)
	at scalaz.stream.Process$$anonfun$pipe$1.apply(Process.scala:143)
	at scalaz.stream.Process$$anonfun$pipe$1.apply(Process.scala:139)
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46)
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$class.flatMap(Process.scala:46)
	at scalaz.stream.Process$Emit.flatMap(Process.scala:592)
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48)
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:53)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:53)
	at scalaz.Free.scalaz$Free$$fastFlatMap(Free.scala:72)
	at scalaz.Free$$anonfun$scalaz$Free$$fastFlatMap$1.apply(Free.scala:73)
	at scalaz.Free$$anonfun$scalaz$Free$$fastFlatMap$1.apply(Free.scala:73)
	at scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187)
	at scalaz.Free.go2$1(Free.scala:134)
	at scalaz.Free.go(Free.scala:137)
	at scalaz.Free.run(Free.scala:187)
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84)
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$class.go$1(Process.scala:84)
	at scalaz.stream.Process$class.step(Process.scala:97)
	at scalaz.stream.Process$Append.step(Process.scala:641)
	at scalaz.stream.Process$class.go$3(Process.scala:482)
	at scalaz.stream.Process$class.runFoldMap(Process.scala:498)
	at scalaz.stream.Process$Append.runFoldMap(Process.scala:641)
	at scalaz.stream.Process$class.runLast(Process.scala:522)
	at scalaz.stream.Process$Append.runLast(Process.scala:641)
	at scalaz.stream.Process$class.runLastOr(Process.scala:527)
	at scalaz.stream.Process$Append.runLastOr(Process.scala:641)
	at org.http4s.jawn.JawnInstances$$anonfun$jawnDecoder$1.apply(JawnInstances.scala:17)
	at org.http4s.jawn.JawnInstances$$anonfun$jawnDecoder$1.apply(JawnInstances.scala:12)
	at org.http4s.EntityDecoder$$anon$3.decode(EntityDecoder.scala:96)
	at org.http4s.EntityDecoder$$anon$2.decode(EntityDecoder.scala:45)
	at org.http4s.client.Client$$anonfun$expect$1.apply(Client.scala:96)
	at org.http4s.client.Client$$anonfun$expect$1.apply(Client.scala:94)
	at org.http4s.client.DisposableResponse.apply(Client.scala:27)
	at org.http4s.client.Client$$anonfun$fetch$1.apply(Client.scala:52)
	at org.http4s.client.Client$$anonfun$fetch$1.apply(Client.scala:52)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36)
	at scalaz.concurrent.Task$.Try(Task.scala:403)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:36)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:34)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future.step(Future.scala:109)
	at scalaz.concurrent.Future.listen(Future.scala:75)
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:53)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:53)
	at scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:61)
	at scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:61)
	at scalaz.Free.resume(Free.scala:86)
	at scalaz.Free.go2$1(Free.scala:133)
	at scalaz.Free.go(Free.scala:137)
	at scalaz.Free.run(Free.scala:187)
	at scalaz.concurrent.Future.listen(Future.scala:76)
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:53)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:53)
	at scalaz.Free.scalaz$Free$$fastFlatMap(Free.scala:72)
	at scalaz.Free$$anonfun$resume$1.apply(Free.scala:88)
	at scalaz.Free$$anonfun$resume$1.apply(Free.scala:88)
	at scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187)
	at scalaz.Free.go2$1(Free.scala:134)
	at scalaz.Free.go(Free.scala:137)
	at scalaz.Free.run(Free.scala:187)
	at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376)
	at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376)
	at org.http4s.client.blaze.Http1Connection.org$http4s$client$blaze$Http1Connection$$parsePrelude(Http1Connection.scala:242)
	at org.http4s.client.blaze.Http1Connection$$anonfun$org$http4s$client$blaze$Http1Connection$$readAndParsePrelude$1.apply(Http1Connection.scala:159)
	at org.http4s.client.blaze.Http1Connection$$anonfun$org$http4s$client$blaze$Http1Connection$$readAndParsePrelude$1.apply(Http1Connection.scala:158)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[trace] Stack trace suppressed: run last compile:run for the full output.
```

**Comment by roboxue** [comment]
I have been digging this issue for a while, not having any clue right now... seems like this is json parsing issue when accepting history server api payload, but I didn't find any significant code change in spark source code between 2.0 and 2.1 yet. Will keep trouble shooting

**Comment by neggert** [comment]
Are you able to reproduce the issue?

**Comment by superbobry** [comment]
Could you provide an event log file causing the issue? This would make it 100% reproducible?

**Comment by neggert** [comment]
I don't think the issue is with any particular log file. I think it's the connection to the history server. I'll double-check, though.

**Comment by roboxue** [comment]
@neggert i'm thinking about the same thing. According to log the exception was thrown when http4s (server lib I'm using) is parsing json payload.

Could call http://<your history server>:<port>/api/v1/applications?status=completed&minDate=2017-05-25, and paste a few lines here (remove sensitive info if needed)

**Comment by alexnikitchuk** [comment]
I have the same issue and it is caused by `startTimeEpoch` value.
Seems like it is caused by another Jawn [issue](https://github.com/non/jawn/issues/69) 
```  
"attempts" : [ {
    "startTime" : "2017-06-05T18:00:17.787GMT",
    "endTime" : "2017-06-05T18:00:50.240GMT",
    "lastUpdated" : "2017-06-05T18:00:50.270GMT",
    "duration" : 32453,
    "sparkUser" : "ubuntu",
    "completed" : true,
    "startTimeEpoch" : 1496685617787,
    "lastUpdatedEpoch" : 1496685650270,
    "endTimeEpoch" : 1496685650240
  } ]```

**Comment by roboxue** [comment]
I see.

Basically, spark 2.0+ added this `xxxEpoch` to the payload

1.6.3: https://github.com/apache/spark/blob/v1.6.3/core/src/test/resources/HistoryServerExpectations/application_list_json_expectation.json

2.0.0:
https://github.com/apache/spark/blob/v2.0.0/core/src/test/resources/HistoryServerExpectations/application_list_json_expectation.json

I'll try to use the payload in spark's testing code to test against my code, and write a manual JSON parsing to bypass the automatic jawn call.

**Comment by alexnikitchuk** [comment]
Using advice from another [issue](https://github.com/non/jawn/issues/72) helped me to fix it locally. I'm ready to push the branch with the fix

**Comment by roboxue** [comment]
Yes please @alexnikitchuk. I'd like to see how you approach it!
